services:

  redis:
    image: redis:7-alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - vote-redis-net
      - worker-backend-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - worker-backend-net
      - result-db-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  vote:
    image: biohazardye/vote:1.0
    ports:
      - "8080:8080"
    environment:
      OPTION_A: ${OPTION_A}
      OPTION_B: ${OPTION_B}
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - vote-redis-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  worker:
    image: biohazardye/worker:1.0
    environment:
      REDIS_HOST: ${REDIS_HOST}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - worker-backend-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  result:
    image: biohazardye/result:1.0
    ports:
      - "8081:80"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - result-db-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
  redis_data:

networks:
  vote-redis-net:
    driver: overlay
  worker-backend-net:
    driver: overlay
  result-db-net:
    driver: overlay